### ISSUE TITLE
DKIM and SPF

### ISSUE THREAD

**Issue by anotherdevs** [ushis/mailhook#10]
Hi

Is it possible to integrate DKIM and SPF checks?

There is a few packages:
https://github.com/toorop/go-dkim
https://github.com/emersion/go-dkim
https://github.com/asggo/spf
https://github.com/mileusna/spf

**Comment by ushis** [comment]
Hi,

i am running mailhook behind Postfix and let handle Postfix DKIM and SPF checks. I would prefer to let a real MTA handle the complex SMTP mechanisms and only receive mails here.

Closing this, ok?
