### ISSUE TITLE
go.enmime has been archived

### ISSUE THREAD

**Issue by anotherdevs** [ushis/mailhook#11]
Hi

github.com/jhillyerd/go.enmime has been archived and replaced with: github.com/jhillyerd/enmime

Would it be possible to move to the new framework?

**Comment by ushis** [comment]
Hi,

thanks for the heads up. They changed a lot of API and i am on a trip and don't have the time to do this right now. I am back this summer and can do the switch or somebody prepares a pull request until then.

Cheers, ushi
